require 'pry'
require 'faker'

User.destroy_all
Game.destroy_all
UserGame.destroy_all



jacqueline = User.create ({username: "Jacqueline", password: "1234", score: 10})
kevin = User.create ({username: "Kevin", password: "5678", score: 5})
bryan = User.create ({username: "Bryan", password: "0234", score: 8})
bob = User.create ({username: "Bob", password: "0234", score: 7})
will = User.create ({username: "Will", password: "0234", score: 6})
carl = User.create ({username: "Carl", password: "0234", score: 1})
rachel = User.create ({username: "Rachel", password: "0234", score: 4})

game1 = Game.create({difficulty: "easy", word: "beans" })
game2 = Game.create({difficulty: "hard", word: "house" })
game3 = Game.create({difficulty: "easy", word: "boat"  })
game4 = Game.create({difficulty: "easy", word: "rain"  })
game5 = Game.create({difficulty: "hard", word: "console"  })
game6 = Game.create({difficulty: "hard", word: "premium"  })
game7 = Game.create({difficulty: "easy", word: "plant"  })
game8 = Game.create({difficulty: "medium", word: "couch"  })
game9 = Game.create({difficulty: "easy", word: "cup"  })
game10 = Game.create({difficulty: "easy", word: "phone" })
game11 = Game.create({difficulty: "hard", word: "collection" })
game12 = Game.create({difficulty: "easy", word: "stay"  })
game13 = Game.create({difficulty: "easy", word: "gas"  })
game14 = Game.create({difficulty: "hard", word: "absolutely"  })
game15 = Game.create({difficulty: "hard", word: "candidates"  })
game16 = Game.create({difficulty: "easy", word: "bee"  })
game17 = Game.create({difficulty: "medium", word: "board"  })
game18 = Game.create({difficulty: "easy", word: "bike"  })
game19 = Game.create({difficulty: "easy", word: "bird" })
game20 = Game.create({difficulty: "hard", word: "maleficent" })
game21 = Game.create({difficulty: "easy", word: "nice"  })
game22 = Game.create({difficulty: "easy", word: "talk"  })
game23 = Game.create({difficulty: "hard", word: "aberration"  })
game24 = Game.create({difficulty: "hard", word: "friendship"  })
game25 = Game.create({difficulty: "easy", word: "tall"  })
game26 = Game.create({difficulty: "medium", word: "reason"  })
game27 = Game.create({difficulty: "easy", word: "food"  })
game28 = Game.create({difficulty: "easy", word: "foot" })
game29 = Game.create({difficulty: "hard", word: "house" })
game30 = Game.create({difficulty: "easy", word: "egg"  })
game31 = Game.create({difficulty: "easy", word: "duck"  })
game32 = Game.create({difficulty: "hard", word: "blancmange"  })
game33 = Game.create({difficulty: "hard", word: "adaptation"  })
game34 = Game.create({difficulty: "easy", word: "late"  })
game35 = Game.create({difficulty: "medium", word: "women"  })
game36 = Game.create({difficulty: "easy", word: "sea"  })
game37 = Game.create({difficulty: "easy", word: "mind" })
game38 = Game.create({difficulty: "hard", word: "apocalypse" })
game39 = Game.create({difficulty: "easy", word: "sing"  })
game40 = Game.create({difficulty: "easy", word: "saw"  })
game41 = Game.create({difficulty: "hard", word: "aboveboard"  })
game42 = Game.create({difficulty: "hard", word: "relaxation"  })
game43 = Game.create({difficulty: "easy", word: "zoo"  })
game44 = Game.create({difficulty: "medium", word: "young"  })
game45 = Game.create({difficulty: "easy", word: "blue"  })


ug1 = UserGame.create({user_id: jacqueline.id, game_id: game1.id, won_game: true })
ug2 = UserGame.create({user_id: carl.id, game_id: game2.id, won_game: true})
ug3 = UserGame.create({user_id: carl.id, game_id: game3.id, won_game: false})
ug4 = UserGame.create({user_id: jacqueline.id, game_id: game4.id, won_game: false})
ug5 = UserGame.create({user_id: kevin.id, game_id: game5.id, won_game: true})
ug6 = UserGame.create({user_id: will.id, game_id: game6.id, won_game: false})
ug7 = UserGame.create({user_id: bob.id, game_id: game7.id, won_game: true})
ug8 = UserGame.create({user_id: jacqueline.id, game_id: game8.id, won_game: true})
ug9 = UserGame.create({user_id: bryan.id, game_id: game9.id, won_game: false})
ug10 = UserGame.create({user_id: jacqueline.id, game_id: game10.id, won_game: true })
ug11 = UserGame.create({user_id: kevin.id, game_id: game11.id, won_game: true})
ug12 = UserGame.create({user_id: carl.id, game_id: game12.id, won_game: false})
ug13 = UserGame.create({user_id: rachel.id, game_id: game13.id, won_game: false})
ug14 = UserGame.create({user_id: kevin.id, game_id: game14.id, won_game: true})
ug15 = UserGame.create({user_id: bob.id, game_id: game15.id, won_game: false})
ug16 = UserGame.create({user_id: will.id, game_id: game16.id, won_game: true})
ug17 = UserGame.create({user_id: rachel.id, game_id: game17.id, won_game: true})
ug18 = UserGame.create({user_id: bryan.id, game_id: game18.id, won_game: false})
ug19 = UserGame.create({user_id: jacqueline.id, game_id: game19.id, won_game: true })
ug20 = UserGame.create({user_id: kevin.id, game_id: game20.id, won_game: true})
ug21 = UserGame.create({user_id: rachel.id, game_id: game21.id, won_game: false})
ug22 = UserGame.create({user_id: will.id, game_id: game22.id, won_game: false})
ug23 = UserGame.create({user_id: kevin.id, game_id: game23.id, won_game: true})
ug24 = UserGame.create({user_id: bob.id, game_id: game24.id, won_game: false})
ug25 = UserGame.create({user_id: kevin.id, game_id: game25.id, won_game: true})
ug26 = UserGame.create({user_id: jacqueline.id, game_id: game26.id, won_game: true})
ug27 = UserGame.create({user_id: bryan.id, game_id: game27.id, won_game: false})
ug28 = UserGame.create({user_id: jacqueline.id, game_id: game28.id, won_game: true })
ug29 = UserGame.create({user_id: kevin.id, game_id: game29.id, won_game: true})
ug30 = UserGame.create({user_id: jacqueline.id, game_id: game30.id, won_game: false})
ug31 = UserGame.create({user_id: rachel.id, game_id: game31.id, won_game: false})
ug32 = UserGame.create({user_id: kevin.id, game_id: game32.id, won_game: true})
ug33 = UserGame.create({user_id: bryan.id, game_id: game33.id, won_game: false})
ug34 = UserGame.create({user_id: kevin.id, game_id: game34.id, won_game: true})
ug35 = UserGame.create({user_id: carl.id, game_id: game35.id, won_game: true})
ug36 = UserGame.create({user_id: bryan.id, game_id: game36.id, won_game: false})
ug37 = UserGame.create({user_id: rachel.id, game_id: game37.id, won_game: true })
ug38 = UserGame.create({user_id: bob.id, game_id: game38.id, won_game: true})
ug39 = UserGame.create({user_id: carl.id, game_id: game39.id, won_game: false})
ug40 = UserGame.create({user_id: will.id, game_id: game40.id, won_game: false})
ug41 = UserGame.create({user_id: will.id, game_id: game41.id, won_game: true})
ug42 = UserGame.create({user_id: bryan.id, game_id: game42.id, won_game: false})
ug43 = UserGame.create({user_id: bob.id, game_id: game43.id, won_game: true})
ug44 = UserGame.create({user_id: jacqueline.id, game_id: game44.id, won_game: true})
ug45 = UserGame.create({user_id: bryan.id, game_id: game45.id, won_game: false})

